apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-python-serverless
  namespace: tienhung17092004-dev
spec:
  template:
    metadata:
      annotations:
        # This tells OpenShift to scale to 0 when no one is visiting
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      containers:
        # I'm using a pre-built image for this example
        - image: image-registry.openshift-image-registry.svc:5000/tienhung17092004-dev/hello-serverless-build:latest
          env:
            - name: TARGET
              value: "K8s Master"
            - name: "APP_FILE"
              value: "app.py"
          ports:
            - containerPort: 8080